### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by toledofernanda** [mcamara01/petbookFirebase#13]
- Notification

**Comment by mcamara01** [comment]
_top right nav doesn't work on pet profile and settings pages_

Maybe is something related to firebase error.. because on pet-profile page and  settings we got the same errors: firebase and top nav.

**Comment by mcamara01** [comment]
**Solved** top right nav doesn't work on pet profile and settings pages

**Comment by mcamara01** [comment]
**Solved** - remove the alert option from allergies, infections, and categories that are not necessary
**Solved** - change the text of pop up from "sure you want to add" to "sure you want to edit" when editing cards

**Comment by mcamara01** [comment]
**Solved** - remove add button while adding or deleting cards

**Comment by mcamara01** [comment]
_- remove "sure to add" popup, just necessary when editing and deleting (can be done for the final version)_ 
This means having to change considerable part of the code, since the id's of the popup are being used on js files.  Think we can do this only if we have enough time left to adjust this detail.

**Done! :)**

**Comment by mcamara01** [comment]
**Solved** - while adding some cards bg color shortens (shows white) and save button disappear, need to close keyboard to see it (ex. infections page)

**Comment by toledofernanda** [comment]
**Solved** - have to click twice to go back to pages (doesn't happen on apk)

**Comment by toledofernanda** [comment]
**Solved** - created terms and conditions page and linked it from create account

// not working on browser! //

**Comment by toledofernanda** [comment]
**Solved** - Settings - removed user photo and phone

**Comment by toledofernanda** [comment]
**Solved** - Remove Plus Button from Settings

**Comment by toledofernanda** [comment]
**Solved -** Remove On-Going on Medication

**Comment by toledofernanda** [comment]
**Solved** - remove "sure to add" popup, just necessary when editing and deleting (can be done for the final version)

**Comment by mcamara01** [comment]
**Solved** - Calendar Plugin

**Comment by mcamara01** [comment]
Notification not going to be implemented on this version
