### ISSUE TITLE
Add pet Page

### ISSUE THREAD

**Issue by toledofernanda** [mcamara01/petbookFirebase#14]
ALL FIXED

**Comment by mcamara01** [comment]
**Solved** - change kg label to kg(s)s - Done

**Comment by toledofernanda** [comment]
**Solved -** change gender input to radio button (male/female)
**Cancelled** - include place holders (ex. a name for a pet: Rex) - is not necessary since it has labels
**Cancelled** - not allow more than 4 digits for year input - we decided that is not necessary to validate these inputs

**Comment by toledofernanda** [comment]
**Solved -** Fixed age and happy bday bug

**Comment by toledofernanda** [comment]
**Solved** - Fixed to not show prev/next arrow if there's only one pet
*can close this issue!
