### ISSUE TITLE
Calendar/Notification

### ISSUE THREAD

**Issue by mcamara01** [mcamara01/petbookFirebase#15]

**Comment by mcamara01** [comment]
=> I ran a test to send feedback from browser.. Didn't receive the message. Checked and our app email was incorrect. Changed in all files. Tested again and we got the feedback message.

**Comment by mcamara01** [comment]
**Solved** Firebase not defined error
**Solved** Menu to send feedback.. not working on settings page

**Comment by toledofernanda** [comment]
**Solved** Menu settings opens window to send message on browser, but not apk (tested apk and is working)
**Solved** removed user photo, phone number and add new button
