### ISSUE TITLE
Layout/Images index page

### ISSUE THREAD

**Issue by mcamara01** [mcamara01/petbookFirebase#3]
Do some adjustments to the layout: 
DONE

**Comment by toledofernanda** [comment]
- The no pet picture and info new icons are in the updated icons folder. I updated the paths of these icons on js file and sass file according to the new icons added.
- DONE The CSS needs to be reviewed for all pages so we have a standard for everything. Think is better to be the last thing to do after everything is ready.
- The window.location is directing to index page and adding image and cancel adding pet were working before the merge, we need to check what happened.

**Comment by mcamara01** [comment]
**Solved** - button cancel delete pet (cancel is not working) - stay frozen
**Solved** - button confirm delete pet - deletes the pet but the page doesn't load again - insert window.location

**Comment by mcamara01** [comment]
**Solved** - button "Next" layout is too different from others (font size too huge)

**Comment by toledofernanda** [comment]
**Solved** - added feature to edit photo
**Solved** - fixed bug that didn't update new name and age calculation after editing them
