### ISSUE TITLE
Notes Page

### ISSUE THREAD

**Issue by mcamara01** [mcamara01/petbookFirebase#4]
After creating a note, the plus button is adding another one.
Decide if we will have 1 or more cards for notes.

- When adding, the input date don't display anything - need to fix it

**Comment by toledofernanda** [comment]
In my opinion is even better it is possible to add more than one, as long as the user can remove it he wants.

**Comment by mcamara01** [comment]
Ok. Just to need to fix the data field to show information that need to be entered instead of blank

**Comment by toledofernanda** [comment]
- Make the date input more visible, the input is there but it can't be seen clearly (maybe automatically insert new Date() ?)
- While adding note text the text area box overflows the screen as well as the text

**Comment by mcamara01** [comment]
**Solved**
