### ISSUE TITLE
General Info Page

### ISSUE THREAD

**Issue by mcamara01** [mcamara01/petbookFirebase#5]
- Dob field while on editing mode, doesn't display the calendar - need to fix it
- Weight in Kg -> General page it comes with no measure unity - need to fix it

**Comment by mcamara01** [comment]
**Solved** - Check color field - when on editing mode, the color entered disappears

**Comment by toledofernanda** [comment]
- When editing gender, color, and weight the data doesn't change (on HTML or database)

**Comment by mcamara01** [comment]
_When editing gender, color, and weight the data doesn't change (on HTML or database)_

I test and for me it changes.. changes on the app and on database. I just tested that changing with database open and it worked. Please let me know if the error persists.

**Comment by mcamara01** [comment]
**Solved** -  Dob field while on editing mode, doesn't display the calendar - need to fix it
**Solved** - Weight in Kg -> General page it comes with no measure unity - need to fix it
